
class UITorrentEnum:
    UI_TORRENT_HASH, \
    UI_TORRENT_STATUS, \
    UI_TORRENT_NAME, \
    UI_TORRENT_SIZE, \
    UI_TORRENT_PERCENT_PROGRESS, \
    UI_TORRENT_DOWNLOADED, \
    UI_TORRENT_UPLOADED, \
    UI_TORRENT_RATIO, \
    UI_TORRENT_UPLOAD_SPEED, \
    UI_TORRENT_DOWNLOAD_SPEED, \
    UI_TORRENT_ETA, \
    UI_TORRENT_LABEL, \
    UI_TORRENT_PEERS_CONNECTED, \
    UI_TORRENT_PEERS_IN_SWARM, \
    UI_TORRENT_SEEDS_CONNECTED, \
    UI_TORRENT_SEEDS_IN_SWARM, \
    UI_TORRENT_AVAILABILITY, \
    UI_TORRENT_TORRENT_QUEUE_ORDER, \
    UI_TORRENT_REMAINING = range(19)